### ISSUE TITLE
Week 5-6 : Experiment Missing

### ISSUE THREAD

**Issue by rishi11** [kethamakka/CS5610-vijayk#10]
Total of 10 experiments should be there for 2 weeks. Please complete.

**Comment by kethamakka** [comment]
Week 5, 6 and 7 will have 15 experiments in total. They were done in their respective weeks but submitted according to their categories. "Week 5 and week 6 experiments" folder has experiments on jQuery and week 7 has experiments in jQueryUI. Please note.
