### ISSUE TITLE
Week 6 : Experiments non functional.

### ISSUE THREAD

**Issue by rishi11** [kethamakka/CS5610-vijayk#8]
Add things on the FLY!
Local Storage and Retrieval
Resizable Components
Set Lisa Straight

Not Working.

**Comment by rishi11** [comment]
Reminder : Please fix !!

**Comment by kethamakka** [comment]
The experiments have been fixed right away. This issue was first raised 18 days ago and it was fixed on the same day. All four experiments are in working condition from that same day!
