### ISSUE TITLE
Week 7 : Experiments not working

### ISSUE THREAD

**Issue by rishi11** [kethamakka/CS5610-vijayk#9]
Experiments : 
Querying a WebAPI
Querying based on a server Template

Non functional !! Please fix.

**Comment by kethamakka** [comment]
Hello rishi,

When i am executing on local machine, i am able to see their functionality
perfectly. I have tried in many ways. i tried deleting the folder and
syncing again. synced the entire experiments folder in to server. When i
execute the experiment in the net4 server, i cant see the functionality. I
need some help regarding this. Can i meet you and get this clarified?

**Comment by rishi11** [comment]
You can meet me or any other TA during office hours.
